# -*- coding: utf-8 -*-
"""Factorial_via_iteration.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-wcEGi4xl1B1dfeevYCqcqU1ecKTWPSJ
"""

# -*- coding: utf-8 -*-
"""
Created on Tue Oct  4 13:19:36 2022

@author: Deepak
"""

def factI(n):
    result = 1
    while n > 1:
        result = result * n
        n -= 1
    return result

factI(4)